name: build

on:
  pull_request:
  push:
    branches:
      - patch-1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compile to module
        shell: pwsh
        run: ./ci.ps1

      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::Nightly_$(date +"%Y.%m.%d_%H-%M")"

      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag.outputs.release_tag }}
          artifacts: "privacy.sexy.ps1"

      # - uses: softprops/action-gh-release@v1
      #   with:
      #     tag_name: ${{ steps.tag.outputs.release_tag }}
      #     fail_on_unmatched_files: true
      #     files: |
      #       ./privacy.sexy.ps1
